astroML/datasets/sdss_filters.py
The link for the SDSS filters were slighty wrong, and the new one is provided as provided in Issue #51.
Cheers,
Daniel
=> Corrected link for SDSS filters

astroML/plotting/scatter_contour.py
Fixes issues in the `scatter_contour()` function where the plot points were hiding my contour plot, and the outline contour plot was still being shown.
=> Scatter contour fixes

astroML/density_estimation/xdeconv.py
Likelihood calculation in xdeconv.py is missing component amplitudes, otherwise seems ok.
=> Use mixture weights when computing likelihoods

astroML/resample.py, astroML/tests/test_resample.py
This is to enable the calculation of the covariance from a bootstrap (currently only diagonals are returned)
=> modified the bootstrap function to allow the passing of n-d arrays 

astroML/datasets/sdss_galaxy_colors.py
When trying to run the code from http://www.astroml.org/examples/learning/plot_neighbors_photoz.html, I ran into some issues when fetching the data. The class of the object is represented as a string instead of an integer and the field is called 'spec' instead of 'specClass'. I changed the text loading function to `genfromtxt`, because it handles string better. I kept the names of the fields the same for backwards compatibility purposes.
=> Fix fetching sdss galaxy colors data

astroML/density_estimation/histtools.py
When trying to plot histograms using the Knuth's rule with astroML
and Python 3.5, I was having a weird error. The error was in line 105 and
106 of `histtools.py`: invalid index. This bug prevented from plotting histograms with the Knuth's rule.
I fixed that with a simple integer conversion.
=> fixed python 3.5 bug about invalid index => histograms w/ Knuth's rule

astroML/density_estimation/__init__.py
Reordered import so
``` python
from astroML.density_estimation import histogram
histogram(x, bins="blocks")
```
works
=> Relative imports in wrong order if you want to use histogram via

setup.py
The upper limits on the supported versions should be added for 0.3.1, but as a start this can go both into the backport and master.
=> Adding dependency versions to setup.py

examples/datasets/compute_sdss_pca.py
Addresses issue raised in #60 by @kareemelbadry in which an infinite loop could be encountered during SDSS spectra resampling if rebinned to all zeros.
Submitting PR since issue has been idle for 1yr.
=> Adds counter increment to prevent infinite loop upon rebin all zero case

.travis.yml, astroML/filters.py
This PR fixes the numpy incompatibility issue surfaced by the tests. 
Tests with newer python and numpy run locally (when tried on top of the fixes from #125), but there may still be some issues when backporting to 0.3.1
=> Fixing numpy compatibility

astroML/plotting/tools.py
I'm not exactly certain how this passed the tests when it was removed in mpl 3.0, but when switching to pytest it trips all travis jobs.
=> Removing deprecated matplotlib API usage

astroML/density_estimation/tests/test_density.py, astroML/density_estimation/tests/test_xdeconv.py, astroML/stats/tests/test_stats.py, astroML/tests/test_fourier.py, astroML/time_series/tests/test_generate.py
They are deprecated in pytest 3, so this PR rewrites them to use parametrize instead.
=> Rewriting yield-based tests 

.travis.yml
The docs build should pass, so adding it to CI. Currently there are tons of warnings due to broken references to the book figures, those need to be fixed.
=> Adding docs build to travis

README.rst, astroML/density_estimation/bayesian_blocks.py, astroML/density_estimation/histtools.py, astroML/density_estimation/tests/test_bayesian_blocks.py, astroML/density_estimation/tests/test_hist_binwidth.py, astroML/plotting/hist_tools.py, doc/user_guide/installation.rst, setup.py
Bayesian blocks has been ported to astropy v1.1 in https://github.com/astropy/astropy/pull/3756. 
This is based on #141, and thus should be rebased once that one is merged.
=> Deprecate histograms

astroML/plotting/settings.py
This should be backwards compatible, so safe to backport to 0.3.1, but on the other hand not crucial.
=> Update the mpl rcparams for mpl 2.0+

astroML/density_estimation/histtools.py, astroML/plotting/hist_tools.py
Leaving the `disp` kwarg was a mistake, it should have been removed in #142. The rest of the changes mostly cosmetic to clean up a few warnings.
=> Some more histogram related fix

.travis.yml, doc/sphinxext/example_builder.py
This has been left out previously.
=> Make the example_builder sphinxext python3 compatible

astroML/cosmology.py, astroML/datasets/generated.py, astroML/datasets/sdss_specgals.py
This PR needs revision, and in it's current stage the rebased and squashed version of #35 with the removal of the figures.
Original commit message:
* Import astropy.cosmology when possible and use instead of
built-in cosmology class.
* Add deprecation warning to built in cosmology
* astropy 0.3.0 or more recent required because the astropy.cosmology
objects return things with units.  This -is- tested for;
if the version is less than 0.3.0, the built in cosmology
class is used instead.
* datasets/generate.generate_mu_z no longer supports optional
**kwargs passed to cosmology object; this would be complicated
to implement when using astropy.cosmology because it takes some
positional (rather than named) arguments.  However, this option
wasn't used in the figures anyways.
* Affected figures …
=> Rebased version of #35: Use astropy.cosmology instead of built-in cosmology when possible

astroML/time_series/periodogram.py
Deprecating LS periodograms from astroML to be removed in 1.0. They have been moved over to astropy and developed further there.
=> Adding deprecations from periodograms

astroML/datasets/LIGO_bigdog.py, astroML/datasets/LINEAR_sample.py, astroML/datasets/dr7_quasar.py, astroML/datasets/imaging_sample.py, astroML/datasets/moving_objects.py, astroML/datasets/nasa_atlas.py, astroML/datasets/rrlyrae_mags.py, astroML/datasets/rrlyrae_templates.py, astroML/datasets/sdss_S82standards.py, astroML/datasets/sdss_corrected_spectra.py, astroML/datasets/sdss_filters.py, astroML/datasets/sdss_galaxy_colors.py, astroML/datasets/sdss_specgals.py, astroML/datasets/sdss_spectrum.py, astroML/datasets/sdss_sspp.py, astroML/datasets/wmap_temperatures.py
This fixes #179 
This PR starts to move the fetchers more towards astropy, e.g. using Table to read in a remote URL, etc.
However on the user side everything is still transparent, as the functions still return numpy arrays.
=> Moving data from UW websites to GitHub

astroML/time_series/periodogram.py
astropy.timeseries is new in v3.2, we import from there when possible.
=> Updating for astropy 3.2 namespace changes

astroML/datasets/LINEAR_sample.py
The name of the column has been changed at some point, this one is now consistent with the file we ship in https://github.com/astroML/astroML-data/
=> Changing name of column to reflext the name in the datafile

astroML/plotting/settings.py
The bug is resurfaced now that the release candidate for mpl 3.1 is out.
=> Fix rc syntax for mpl 3.1

astroML/correlation.py, astroML/datasets/tools/cas_query.py
The minimum required version is 0.18 in 0.4, so the workaround can be removed.
=> Cleaning up sklearn <0.14 workaround

astroML/filters.py, astroML/tests/test_filters.py, doc/user_guide/installation.rst
Adhering to the TODO comment in the source code, we shall remove this function and promote the usage of the scipy equivalent instead.
=> Deprecate savitzky_golay

README.rst
The current link to Numpy Documentation Guide points to the `doctring` section.
This PR removes the anchor to make the link go to the base formatting page.
=> Change numpy doc guide link

astroML/datasets/LIGO_bigdog.py, astroML/datasets/LINEAR_sample.py, astroML/datasets/dr7_quasar.py, astroML/datasets/imaging_sample.py, astroML/datasets/moving_objects.py, astroML/datasets/rrlyrae_mags.py, astroML/datasets/sdss_S82standards.py, astroML/datasets/sdss_specgals.py, astroML/datasets/sdss_sspp.py
These datasets require a download and therefore should be marked with `+REMOTE_DATA`. This caused a failure during the Debian build.
I removed the original comment here since they seem obvious to me (and I was not sure how to combine them with the doctest option ;-) ).
=> Mark dataset examples as remote data

.travis.yml, astroML/classification/gmm_bayes.py, astroML/conftest.py, astroML/density_estimation/tests/test_density.py, pytest.ini, setup.cfg, setup.py
Changes is sklearn 0.22 affects functionality, the quick fix is in this PR for it. Longer term we need to move on from subclassing `BaseNB` as it got deprecated in 0.22
Minor fixes to make tests pass with astropy 4.0, numpy 1.18.
=> Fix compatibility with recently released upstream libraries

.travis.yml, doc/user_guide/installation.rst, setup.py
These versions were required in the updated edition of the book for those examples, etc, and most of them are already hard requirements for code updates that rely on newer API of dependencies.
=> Update requirements 

.travis.yml
this is in fact an upstream issue, ci-helpers sets up the environment with some basic packages when astropy is installed, e.g. pytest-astropy. However the latest version of pytest-doctestplus (0.8.0), that is compatible with pytest 6.0 is not available on defaults, so the 0.7.0 is picked up that is causing the CI failures here. 
Adding this workaround until better upstream solution comes up.
=> TST: Fixing doctestplus pytest incompatibility for CI

CHANGES.rst, astroML/datasets/__init__.py, astroML/datasets/sdss_galaxy_images.py
To download  `sdss_images_1000.npy` needed for the CNN figure: http://www.astroml.org/book_figures/chapter9/fig_morph_nn.html
(figure also needs updating to use this function, it will be in a separate PR for the other repo).
@connolly - could you please double check that I did get the source of the data right?
=> Adding fetch_sdss_galaxy_images

.gitignore, CHANGES.rst, README.rst, astroML/dimensionality/iterative_pca.py, doc/user_guide/installation.rst, setup.cfg, tox.ini
Technically we can wait a little bit more, but I would err on the side of fixing this sooner rather than later.  This fixes #265 
```
Deprecated since version 0.19.0: This keyword is deprecated and should be replaced by using assume_a = 'pos'. sym_pos will be removed in SciPy 1.11.0.
```
We likely need to bump the minimum required version of scipy to 0.19, will do it once this need is confirmed by CI. 0.19 has been first released in Mar 2017, so I don't see any controversy in bumping the requirement.
=> MAINT: Update deprecated usage of scipy arguments

.github/workflows/ci_tests.yaml, setup.cfg
The docs build started to fail in the latest cron job, I expect this should fix the latex install. 
The PR also includes another minor config typo
=> CI: fix latex install for failing docs build
