astroML/astroML

- astroML/time_series/tests/test_generate.py
- astroML/time_series/tests/test_periodogram.py
> Test between native and addon lombscargle

- astroML/density_estimation/gauss_mixture.py
- astroML/density_estimation/tests/test_density.py
- astroML/stats/tests/test_stats.py
- astroML/time_series/tests/test_periodogram.py
Added tests for trunc_exp and linear_gen. Wanted to ensure that at least they're zero outside the given bounds, and that the probability distribution functions roughly integrate to 1
> TST: stats.random

- .travis.yml
I know that this may be an unwanted change; if so please just close the PR.
> Updating travis to use the latest miniconda script and the container based infrastructure

- .travis.yml
Adding new python versions to the testing. 
The matrix should probably be further fragment to test for different np, sklearn, astropy versions, so I'm considering to switch to use ci-helpers here.
> Refactoring CI matrix

- examples/datasets/plot_moving_objects.py
> Clarify title of example

- .travis.yml
- astroML/conftest.py
- astroML/plotting/tools.py
I suppose there are still some nose specific stuff to clean up in the tests themselves, but this works out of the box locally, so if CI is happy it can go in now as is.
> Switching to use pytest

- doc/conf.py
- doc/sphinxext/example_builder.py
- doc/sphinxext/exfile.py
- doc/sphinxext/numpy_ext/__init__.py
- doc/sphinxext/numpy_ext/docscrape.py
- doc/sphinxext/numpy_ext/docscrape_sphinx.py
- doc/sphinxext/numpy_ext/numpydoc.py
- doc/sphinxext/numpy_ext/templates/numpydoc_docstring.rst
Some updates are needed to be able to build the docs with current sphinx and python versions.
> Update sphinx extensions

- astroML/datasets/LIGO_bigdog.py
- astroML/datasets/LINEAR_sample.py
- astroML/datasets/dr7_quasar.py
- astroML/datasets/imaging_sample.py
- astroML/datasets/moving_objects.py
- astroML/datasets/nasa_atlas.py
- astroML/datasets/rrlyrae_mags.py
- astroML/datasets/rrlyrae_templates.py
- astroML/datasets/sdss_S82standards.py
- astroML/datasets/sdss_corrected_spectra.py
- astroML/datasets/sdss_filters.py
- astroML/datasets/sdss_galaxy_colors.py
- astroML/datasets/sdss_specgals.py
- astroML/datasets/sdss_sspp.py
- astroML/datasets/tools/cas_query.py
- astroML/datasets/tools/download.py
- astroML/datasets/tools/sdss_fits.py
- astroML/datasets/wmap_temperatures.py
This PR starts using the new `astroML-data` repo. 
In addition minor code cleanup, and PEP8 fixes.
> Fixing broken dataset URLs

- astroML/datasets/sdss_galaxy_colors.py
- astroML/datasets/tools/cas_query.py
- astroML/datasets/wmap_temperatures.py
- astroML/stats/_binned_statistic.py
- examples/algorithms/fig_volume_ratio.py
- examples/algorithms/plot_bayesian_blocks.py
- examples/algorithms/plot_crossmatch.py
- examples/datasets/compute_sdss_pca.py
- examples/datasets/plot_LIGO_spectrum.py
- examples/datasets/plot_moving_objects.py
- examples/datasets/plot_nasa_atlas.py
- examples/datasets/plot_sdss_galaxy_colors.py
- examples/datasets/plot_sdss_specgals.py
- examples/learning/plot_neighbors_photoz.py
Now all (except #149, but that can be addressed later) should work even with cleaned cache (~/astroML_data).
Locally tested with python3.7 and python2.7
Some of these may be backported to the 0.3.x branch.
> Fix examples

- .travis.yml
- astroML/datasets/LIGO_bigdog.py
- astroML/datasets/LINEAR_sample.py
- astroML/datasets/dr7_quasar.py
- astroML/datasets/imaging_sample.py
- astroML/datasets/moving_objects.py
- astroML/datasets/rrlyrae_mags.py
- astroML/datasets/sdss_S82standards.py
- astroML/datasets/sdss_specgals.py
- astroML/datasets/sdss_spectrum.py
- astroML/datasets/sdss_sspp.py
- astroML/density_estimation/bayesian_blocks.py
- astroML/filters.py
- astroML/fourier.py
- astroML/linear_model/TLS.py
- astroML/plotting/tools.py
- astroML/stats/_binned_statistic.py
- astroML/time_series/tests/test_periodogram.py
- astroML/utils/decorators.py
- astroML/utils/tests/test_utils.py
- pytest.ini
- setup.cfg
This is WIP as the failing tests should be fixed before merging.
> Enabling doctesting

- astroML/datasets/generated.py
- astroML/datasets/sdss_specgals.py
These could have been part of #121
> Cosmology minor cleanup

- .travis.yml
- astroML/datasets/sdss_specgals.py
- astroML/datasets/tests/test_datasets.py
> z as band is not the same as z as redshift

- astroML/classification/gmm_bayes.py
- astroML/classification/tests/test_gmm_bayes.py
- astroML/linear_model/tests/test_kernel_regression.py
- astroML/tests/test_correlation.py
- astroML/utils/tests/test_utils.py
- doc/user_guide/correlation_functions.rst
Added a couple of tests for 
`astroML/classification/gmm_bayes` and `astroML/correlation` and `astroML/linear_model/kernel_regression`.
> increase test coverage

- CHANGES.rst
- astroML/correlation.py
- astroML/datasets/generated.py
- astroML/density_estimation/empirical.py
- astroML/density_estimation/xdeconv.py
- astroML/resample.py
- astroML/time_series/generate.py
- astroML/time_series/periodogram.py
- astroML/utils/tests/test_utils.py
- astroML/utils/utils.py
> Deprecate utils.check_random_state

- README.rst
Some websites such as the site of this project do not have the automatic http to https redirect, so I changed all the links to https.
> Replace http:// with https://

- astroML/clustering/mst_clustering.py
- astroML/density_estimation/density_estimation.py
- astroML/density_estimation/xdeconv.py
- astroML/linear_model/kernel_regression.py
- astroML/linear_model/linear_regression.py
As previously suggested, subclass `sklearn.base.BaseEstimator` for several classes to get pretty print results.
> Add __repr__ for classes [fix: #159]

- .travis.yml
- astroML/linear_model/linear_regression_errors.py
Minor updates to avoid deprecation warnings and unrelated version incompatibilities
> MNT: Version compatibilities

- doc/conf.py
- doc/user_guide/regression.rst
The website is not part of the package, so factoring this out from #206.
~The binder url's need to be fixed before merging (e.g. merge the website PR, first, then update this.)~ edit: for now the link remains, the notebooks will ultimately live in astroml/astroml-notebooks. Update the link to point there in a follow-up.
> Adding regression docs

- CHANGES.rst
- astroML/lumfunc.py
- astroML/tests/test_lumfunc.py
> Fixing division by zero in Cminus

- README.rst
- astroML/linear_model/linear_regression_errors.py
- astroML/plotting/settings.py
- astroML/plotting/tools.py
- astroML/utils/decorators.py
- doc/user_guide/installation.rst
- setup.cfg
We may need to drop support for a few old versions in favour of making things easier with new versions. I'll keep this PR incremental to find the minimum of updates that passes all CI.
> Compatibility updates for 1.0.2

- astroML/datasets/tools/sdss_fits.py
- tox.ini
This is to close #255 and to get CI green again
> Fix scipy deprecation

- astroML/tests/test_resample.py
This fixes #276 by removing the only usage of the ofending function.
> Delete usage of function removed from numpy>=1.25
